#! /bin/sh
# /etc/init.d/concentrator


# . /etc/rc.d/init.d/functions  # uncomment/modify for your killproc

DAEMON=/home/pi/github/wisense/concentrator/concentrator.py
DIR=/home/pi/github/wisense/concentrator/
NAME=concentrator
D_OPTS='5001 /home/pi/git/wisenseweb/data.sqlite3'

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting concentrator: "
    start-stop-daemon -d $DIR --start -b --exec $DAEMON -- $D_OPTS
    ;;
    stop)
    echo -n "Shutting down concentrator:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    ;;

    restart)
    echo -n "Restarting concentrator: "
    start-stop-daemon -d $DIR --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon -d $DIR --start -b --exec $DAEMON -- $D_OPTS
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0

