#! /bin/sh
# /etc/init.d/rf24sense-dbus


# . /etc/rc.d/init.d/functions  # uncomment/modify for your killproc

DAEMON=/home/pi/github/wisense/rf24sense-dbus/rf24sense
DIR=/home/pi/github/wisense/rf24sense-dbus/
NAME=rf24sense-dbus
D_OPTS='-v'

test -x $DAEMON || exit 0

case "$1" in
    start)
    echo -n "Starting rf24sense: "
    start-stop-daemon -d $DIR --start -b --exec $DAEMON -- $D_OPTS
    echo "rf24sense."
    ;;
    stop)
    echo -n "Shutting down rf24sense:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    echo "rf24sense."
    ;;

    restart)
    echo -n "Restarting rf24sense: "
    start-stop-daemon -d $DIR --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon -d $DIR --start -b --exec $DAEMON -- $D_OPTS
    echo "rf24sense."
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0

